name: spotify_mobile_sdk
description: A Flutter plugin that interacts with the Spotify Mobile SDK
version: 0.1.2
repository: "https://github.com/augu1352/flutter_spotify_mobile_sdk"
issue_tracker: "https://github.com/augu1352/flutter_spotify_mobile_sdk/issues"

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ^1.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.mlohnrob.FlutterSpotifySDK.spotify_mobile_sdk
        pluginClass: SpotifyMobileSdkPlugin
      ios:
        pluginClass: SpotifyMobileSdkPlugin
